version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nifreebie
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: web-4
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: